#!/usr/bin/env bash

# Generates DR2 catalogs

# Get script path
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  GSDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$GSDIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
GSDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Locations
LOGS_LOC="$GSDIR/dr2_logs"
DATA_LOC="$HOME/gaiadata"
DR_BASE="$DATA_LOC/DR2"
DR_LOC="$DR_LOC/dr2"

# Column names (see ColId)
COLS="sourceid,ra,dec,pllx,ra_err,dec_err,pllx_err,pmra,pmdec,radvel,pmra_err,pmdec_err,radvel_err,gmag,bpmag,rpmag,ref_epoch,teff,radius,ag,ebp_min_rp"

source catalogs-gen.sh
