DSNAME="001_$(date +'%Y%m%d')_edr3int2-small"
nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --pllxerrbright 0.1 --pllxerrfaint 0.005 --hip --pllxzeropoint -0.02 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out 
#DSNAME="002_$(date +'%Y%m%d')_edr3int2-default"
#nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/gc/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --pllxerrbright 0.2 --pllxerrfaint 0.005 --hip --pllxzeropoint -0.02 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out
#DSNAME="003_$(date +'%Y%m%d')_edr3int2-bright"
#nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/gc/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --pllxerrbright 0.9 --pllxerrfaint 0.0 --hip --pllxzeropoint -0.02 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out
#DSNAME="004_$(date +'%Y%m%d')_edr3int2-large"
#nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/gc/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --pllxerrbright 0.5 --pllxerrfaint 0.125 --hip --pllxzeropoint -0.02 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out
#DSNAME="005_$(date +'%Y%m%d')_edr3int2-verylarge"
#nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/gc/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --pllxerrbright 0.9 --pllxerrfaint 0.9 --hip --pllxzeropoint -0.02 --postprocess --childcount 10000 --parentcount 50000 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out
#DSNAME="006_$(date +'%Y%m%d')_edr3int2-extralarge"
#nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/gc/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --hip --pllxzeropoint -0.02 --geodistfile /home/sagrista/gaiadata/DR2/geo_distances/ --postprocess --childcount 10000 --parentcount 50000 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out
#DSNAME="007_$(date +'%Y%m%d')_edr3int2-ratherlarge"
#nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/gc/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --pllxerrbright 0.5 --pllxerrfaint 0.5 --hip --pllxzeropoint -0.02 --postprocess --childcount 1000 --parentcount 50000 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out
#DSNAME="008_$(date +'%Y%m%d')_edr3int2-ruwe"
#nohup ./octreegen --loader CsvCatalogDataProvider --input /home/sagrista/gaiadata/eDR3/int2/gc/csv/ --output /home/sagrista/gaiadata/eDR3/int2/out/$DSNAME/ --maxpart 100000 --ruwe 1.4 --ruwe-file /home/sagrista/gaiadata/DR2/ruwe/ruwes.txt.gz --hip --pllxzeropoint -0.02 --postprocess --childcount 1000 --parentcount 50000 --magcorrections --xmatchfile data/gdr2hip/gdr2-hip-xmatch-all.csv > edr3int2_logs/$DSNAME.out
