#!/bin/bash
# Updated: Wed Apr 10 21:04:12 2013 by webmaster@askapache
# @ http://uploads.askapache.com/2013/04/gnu-mirror-index-creator.txt
# Copyright (C) 2013 Free Software Foundation, Inc.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

#    $1 location, ending with '/'
#    $2 directory name
#    $3 domain or server, 'subdomain.domain.tld'
#    $4 title
#    $5 optional, -r for recursive generation
function create_gnu_index ()
{
    # call it right or die
    [[ $# < 3 ]] && echo "Usage: dir2html LOCATION DIRNAME DOMAIN [TITLE] [-r]"
    
		[[ $# < 3 ]] && echo 
    [[ $# < 3 ]] && echo "Options:"
    [[ $# < 3 ]] && echo "    LOCATION - folder to create the index file. End it with a slash '/'"
    [[ $# < 3 ]] && echo "    DIRNAME  - path name at the top of the listing"
    [[ $# < 3 ]] && echo "    DOMAIN   - domain or server name"
    [[ $# < 3 ]] && echo "    TITLE    - optional, document title"
    [[ $# < 3 ]] && echo "    -r       - optional, recursively generate indices"

    [[ $# < 3 ]] && echo 
    [[ $# < 3 ]] && echo "Example: dir2html '/dataB/gaiasky/files/releases/' '/releases' 'gaia.ari.uni-heidelberg.de/gaiasky' 'Gaia Sky repository'" && exit 2
  
		# Set title
		if [[ $# < 4 ]]; then
			TITLE='Gaia Sky repository'
		else
			TITLE=$4
		fi

    # D is the doc_root containing the site
    local L= D="$1" SUBDIR="$2" DOMAIN="$3" F=

    # The index.html file to create
    F="${D}index.html"

    # if dir doesnt exist, create it
    [[ -d $D ]] || mkdir -p $D;

    # cd into dir or die
    cd $D || exit 2;

    # touch index.html and check if writable or die
    touch $F && test -w $F || exit 2;

    # remove empty directories, they dont need to be there and slow things down if they are
    #find . -maxdepth 1 -type d -empty -exec rm -rf {} \;

    # start of total output for saving as index.html
    (

        # print the html header
        echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">';
        echo "<html><head><link rel='stylesheet' href='/gaiasky/style/default.css'/><title>${TITLE}</title></head>";
	echo "<body><h1>${TITLE} - Index of ${SUBDIR}</h1><pre>      Name                                                                      Last modified      Size";

        # start of content output
        (
            # change IFS locally within subshell so the for loop saves line correctly to L var
            IFS=$'\n';

            # pretty sweet, will mimick the normal apache output
            for L in $(find -L . -mount -depth -maxdepth 1 -type f ! -name 'index.html' ! -name 'template.html' ! -name "gaiasky-data.json" -printf "      <a href=\"%f\">%-74f@_@%Td-%Tb-%TY %Tk:%TM  @%f@\n"|sort|sed 's,\([\ ]\+\)@_@,</a>\1,g');
            do
                # file
                F=$(sed -e 's,^.*@\([^@]\+\)@.*$,\1,g'<<<"$L");

                # file with file size
                F=$(du -bh $F | cut -f1);

                # output with correct format
                sed -e 's,\ @.*$, '"$F"',g'<<<"$L";
            done;
        )

        # now output a list of all directories in this dir (maxdepth 1) other than '.', 'webgl' and 'focalplane' and 'videos' and 'gaiasky' and 'webgl.bak' and 'files' outputting in a sorted manner exactly like apache
        find -L . -mount -depth -maxdepth 1 -type d ! -name '.' ! -name 'webgl' ! -name 'focalplane' ! -name 'videos' ! -name 'gaiasky' ! -name 'webgl.bak' ! -name 'files' ! -name 'javadoc' ! -name "other" ! -name "gaiasky-data" -printf "      <a href=\"%f\">%-73f@_@%Td-%Tb-%TY %Tk:%TM  -\n"|sort -d|sed 's,\([\ ]\+\)@_@,/</a>\1,g'

        # print the footer html
        echo "</pre><address>Server at ${DOMAIN}</address></body></html>";

    # finally save the output of the subshell to index.html
    )  > $F;
		
		# Make readable to all
		chmod a+r $1index.html

		echo "Created $1index.html"

		# Recursive?
		if [[ $# > 4 ]] && [[ $5 == "-r" ]]; then
			for i in $(find $L -maxdepth 1 -mindepth 1 -type d)
			do
				CDIR="$(basename -- $i)"
				#echo "create_gnu_index $1$CDIR/ $2$CDIR/ $3 $4 $5"
				create_gnu_index "$1$CDIR/" "$2$CDIR/" "$3" "$4" "$5"
			done
		fi

}




# start the run (use function so everything is local and contained)
#    $1 location, ending with '/'
#    $2 directory name
#    $3 domain or server, 'subdomain.domain.tld'
#    $4 title
#    $5 optional, -r for recursive generation
create_gnu_index "$@"

# takes about 1-5 seconds to complete
exit
