#!/bin/bash

# This script generates the changelog and appends the old-style changelog since 2.2.3

# Utils dir, with a relative path core/utils/ to the root gaiasky directory
UTILSDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
GSDIR=`realpath $UTILSDIR/../../../`

# Use regexp to only include full versions (e.g. exclude release candidates)
git-chglog --tag-filter-pattern '^(\d+\.)?(\d+\.)?(\*|\d+)$' -c $GSDIR/.chglog/config.yml -o $GSDIR/temp.md 3.0.1..
cat $GSDIR/temp.md $UTILSDIR/CHANGELOG-to-300.md > $GSDIR/CHANGELOG.md
rm $GSDIR/temp.md

echo "Changelog generated to $GSDIR/CHANGELOG.md"
