#!/bin/bash

# This script generates the changelog and appends the old-style changelog since 2.0.3

# Utils dir, with a relative path core/utils/ to the root gaiasky directory
UTILSDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
GSDIR=`realpath $UTILSDIR/../../../`

git-chglog -c $GSDIR/.chglog/config.yml -o $GSDIR/temp.md 2.1.7..
cat $GSDIR/temp.md $UTILSDIR/CHANGELOG-to-216.md > $GSDIR/CHANGELOG.md
rm $GSDIR/temp.md

echo "Changelog generated to $GSDIR/CHANGELOG.md"
