#!/bin/bash

# This script pushes the local gaiasky-data.json to the server.
# You must have the right private ssh key to connect.

if [ $# -lt 1 ]; then
    echo "$0"
    echo "Usage:"
    echo "   $0 version"
    echo "Example:"
    echo "   $0 005"
    exit 1
fi

# Directory where script is
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Copy to server
scp $DIR/gaiasky-data.json tsagrista@mintaka:/dataB/gaiasky/files/autodownload/gaiasky-data/gaiasky-data_v$1.json


# Generate and upload mini JSON if we can
if type minify >/dev/null; then
    echo "Generating mini version"
    minify -o $DIR/gaiasky-data.min.json $DIR/gaiasky-data.json
    scp $DIR/gaiasky-data.min.json tsagrista@mintaka:/dataB/gaiasky/files/autodownload/gaiasky-data/gaiasky-data_v$1.min.json
    rm $DIR/gaiasky-data.min.json
fi
echo "Done"
